config/routes.rb
Rails.application.routes.draw do
  resources :gulucas

end

app/models/guluca.rb
class Guluca < ActiveRecord::Base
	validates :nombre, presence: true
	validates :correo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gulucas_controller.rb
class GulucasController < ApplicationController
  before_action :set_guluca, only: [:show, :edit, :update, :destroy]

  # GET /gulucas
  # GET /gulucas.json
  def index
    @gulucas = Guluca.all
  end

  # GET /gulucas/1
  # GET /gulucas/1.json
  def show
  end

  # GET /gulucas/new
  def new
    @guluca = Guluca.new
  end

  # GET /gulucas/1/edit
  def edit
  end

  # POST /gulucas
  # POST /gulucas.json
  def create
    @guluca = Guluca.new(guluca_params)

    respond_to do |format|
      if @guluca.save
        format.html { redirect_to @guluca, notice: 'Guluca was successfully created.' }
        format.json { render json: @guluca }
      else
        format.html { render action: 'new' }
        format.json { render json: @guluca.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gulucas/1
  # PATCH/PUT /gulucas/1.json
  def update
    respond_to do |format|
      if @guluca.update(guluca_params)
        format.html { redirect_to @guluca, notice: 'Guluca was successfully updated.' }
        format.json { render json: @guluca }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guluca.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gulucas/1
  # DELETE /gulucas/1.json
  def destroy
    @guluca.destroy
    respond_to do |format|
      format.html { redirect_to gulucas_url, notice: 'Guluca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guluca
      @guluca = Guluca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guluca_params
      params.require(:guluca).permit(:nombre, :correo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gulucas_helper.rb
module GulucasHelper
end

app/views/gulucas/_form.html.erb
<%= form_for(@guluca, remote: true, format: :json, html: {class: :guluca_form}) do |f| %>

  <div id="error_explanation" style='display:none;'>
    <ul>
      <% if @guluca.errors.any? %>
        <% @guluca.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gulucas/edit.html.erb
<h1>Editing guluca</h1>

<%= render 'form' %>

<%= link_to 'Show', @guluca %> |
<%= link_to 'Back', gulucas_path %>

app/views/gulucas/index.html.erb
<h1>Listing gulucas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gulucas.each do |guluca| %>
      <tr>
        <td><%= guluca.nombre %></td>
        <td><%= guluca.correo %></td>
        <td><%= link_to 'Show', guluca %></td>
        <td><%= link_to 'Edit', edit_guluca_path(guluca) %></td>
        <td><%= link_to 'Destroy', guluca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guluca', new_guluca_path %>

app/views/gulucas/new.html.erb
<h1>New guluca</h1>

<%= render 'form' %>

<%= link_to 'Back', gulucas_path %>

app/views/gulucas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @guluca.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @guluca.correo %>
</p>

<%= link_to 'Edit', edit_guluca_path(@guluca) %> |
<%= link_to 'Back', gulucas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uca</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>